### ISSUE TITLE
Error when modifying actor

### ISSUE THREAD

**Issue by elwis** [bladecoder/bladecoder-adventure-engine#28]
I'm following the tutorial at youtube. When choosing my bgactor and creating the "lookat" verb it crashes as soon as I choose the "Say" action, some empty array perhaps!?

```
EDITOR: ScnWidget Listener: ACTOR_SELECTED
EDITOR: ScnWidget Listener: ACTOR_SELECTED
EDITOR: ACTOR_SELECTED NEW:
Object: door
  Visible: true
  BBox: com.badlogic.gdx.math.Polygon@3dc94ebe
  State: null
  Desc: @00.door.desc_
  Verbs: lookat
 OLD:null
Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 0 >= 0
        at com.badlogic.gdx.utils.Array.get(Array.java:127)
        at com.bladecoder.engineeditor.ui.components.EditableSelectBox.setSelectedIndex(EditableSelectBox.java:108)
        at com.bladecoder.engineeditor.ui.components.ActorInputPanel.<init>(ActorInputPanel.java:39)
        at com.bladecoder.engineeditor.ui.components.InputPanelFactory.createInputPanel(InputPanelFactory.java:66)
        at com.bladecoder.engineeditor.ui.components.InputPanelFactory.createInputPanel(InputPanelFactory.java:57)
        at com.bladecoder.engineeditor.ui.EditActionDialog.setAction(EditActionDialog.java:137)
        at com.bladecoder.engineeditor.ui.EditActionDialog.access$000(EditActionDialog.java:41)
        at com.bladecoder.engineeditor.ui.EditActionDialog$1.changed(EditActionDialog.java:72)
        at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
        at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:181)
        at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:146)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.fireChangeEvent(Selection.java:190)
        at com.badlogic.gdx.scenes.scene2d.utils.Selection.choose(Selection.java:52)
        at com.badlogic.gdx.scenes.scene2d.utils.ArraySelection.choose(ArraySelection.java:40)
        at com.badlogic.gdx.scenes.scene2d.ui.SelectBox$SelectBoxList$2.clicked(SelectBox.java:360)
        at com.badlogic.gdx.scenes.scene2d.utils.ClickListener.touchUp(ClickListener.java:89)
        at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:58)
        at com.badlogic.gdx.scenes.scene2d.Stage.touchUp(Stage.java:353)
        at com.badlogic.gdx.backends.lwjgl.LwjglInput.processEvents(LwjglInput.java:332)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:215)
        at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:124)


```
![image](https://cloud.githubusercontent.com/assets/427954/14213498/8effbcc4-f838-11e5-9b9b-487bc7fff317.png)

**Comment by bladecoder** [comment]
Since v0.9.8 Say action must be used only for character actors, for bg actors you have to use Lookat or Text actions. 

However. there was an bug when no character actors exists in your scene (and you choose the Say action) that produces the error that you describe. It is fixed now.

Thank you!
