### ISSUE TITLE
Exception when trying to launch the Adventure Composer on Linux

### ISSUE THREAD

**Issue by geecko86** [bladecoder/bladecoder-adventure-engine#4]
Hi, I'm eager to play around with the Adventure Composer but this is what happens when I launch it on Linux x64 with OpenJDK 7 (this is with Adventure Composer release 0.8.1).

    geecko@archvaio bin: ./adventure-composer
    Exception in thread "LWJGL Application" java.lang.ExceptionInInitializerError
		at com.badlogic.gdx.backends.lwjgl.LwjglGraphics.setVSync(LwjglGraphics.java:446)
		at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:118)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
		at org.lwjgl.opengl.LinuxDisplay.getAvailableDisplayModes(LinuxDisplay.java:954)
		at org.lwjgl.opengl.LinuxDisplay.init(LinuxDisplay.java:738)
		at org.lwjgl.opengl.Display.<clinit>(Display.java:138)
		... 2 more
	AL lib: (EE) alc_cleanup: 1 device not closed

I assume this is a problem with my setup, but I can't figure it out. I tried running it as root as well. I couldn't find any instructions/dependencies. Hope you won't mind giving me a hand. :)

Awesome project, by the way!

**Comment by bladecoder** [comment]
Hi,

I tested the Adventure Composer v0.8.1 in Ubuntu 15.04 with the OpenJDK  "1.7.0_79" version and it works well for me.

The error in the stack trace seems like a problem initializing the graphics system ¿Maybe is a problem with your graphic drivers?

**Comment by geecko86** [comment]
For those who encounter the same issue, I had to install the "xorg-xrandr" package on my Arch Linux system.

**Comment by JulienBe** [comment]
Don't know how you find the answer, but I love you ! <3
